import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import { readFileSync } from "fs";
import { resolve } from "path";

/**
 * Rollup config for Google Apps Script.
 *
 * Key constraints:
 * - Apps Script expects a flat set of .gs files with top-level functions.
 * - There is no module system on the server — output must be IIFE or plain script.
 * - Any NPM packages used must be inlined (no dynamic require/import at runtime).
 * - Functions that Apps Script needs to call (onOpen, triggers, sidebar RPC endpoints)
 *   must be global — Rollup's IIFE wrapper will scope them unless we handle it.
 *
 * The "footer" trick below closes the IIFE early and re-exposes our entry-point
 * exports as global functions so Apps Script can find them.
 *
 * Config 2 compiles the client-side sidebar TypeScript, then uses the
 * inlineSidebarHtml plugin to assemble dist/Sidebar.html by inlining the
 * compiled JS and sidebar.css into src/Sidebar.html (template).
 * The intermediate JS chunk is deleted so clasp never pushes it as a .gs file.
 */

/**
 * Extracts the major version number from package.json (e.g. "8.0.0" -> "8").
 * This is the single source of truth for the sidebar's displayed version —
 * see the {{VERSION}} placeholder in tool-list.ts's footer.
 */
function readMajorVersion() {
  const pkg = JSON.parse(readFileSync(resolve("package.json"), "utf-8"));
  return pkg.version.split(".")[0];
}

/**
 * Inline plugin: assembles dist/Sidebar.html from template + compiled JS + CSS.
 */
function inlineSidebarHtml({ template, css }) {
  return {
    name: "inline-sidebar-html",
    buildStart() {
      this.addWatchFile(resolve(css));
      this.addWatchFile(resolve(template));
      this.addWatchFile(resolve("package.json"));
    },
    generateBundle(_options, bundle) {
      const chunkKey = Object.keys(bundle).find((k) => bundle[k].type === "chunk");
      const rawCode = chunkKey ? bundle[chunkKey].code : "";

      const templateContent = readFileSync(resolve(template), "utf-8");
      const cssContent = readFileSync(resolve(css), "utf-8");
      const version = readMajorVersion();

      // Replacer functions (not plain strings) — String.replace() treats a string
      // replacement's "$" sequences specially ($$, $&, $1, etc.), which would
      // silently corrupt any such sequence occurring in the compiled JS or CSS
      // (e.g. a literal "$" immediately before a template-literal interpolation).
      const code = rawCode.replace("{{VERSION}}", () => version);
      const assembled = templateContent
        .replace("{{STYLES}}", () => `<style>\n${cssContent}\n</style>`)
        .replace("{{SCRIPTS}}", () => `<script>\n${code}\n</script>`);

      this.emitFile({ type: "asset", fileName: "Sidebar.html", source: assembled });

      if (chunkKey) delete bundle[chunkKey];
    },
  };
}

export default [
  // ── Config 1: Server bundle (unchanged) ─────────────────────────────────────
  {
    input: "src/server/index.ts",
    output: {
      dir: "dist",
      format: "iife",
      name: "_GASEntry",
      inlineDynamicImports: true,
      sourcemap: true,
      banner: "/* Apps Script Bundle — generated by Rollup. Do not edit. */",
      footer: `
/**
 * Global Handshake — Explicit function stubs for Google Apps Script discovery.
 *
 * Every export from index.ts that Apps Script needs to call must have a
 * matching one-line stub here. Rollup's IIFE wrapper scopes everything inside
 * _GASEntry; these stubs re-expose the relevant functions in the global scope.
 */
function onOpen(e) { _GASEntry.onOpen(e); }
function showSidebar() { _GASEntry.showSidebar(); }
function formatMarkdownSelection() { _GASEntry.formatMarkdownSelection(); }
function runTool(fn, jobId) { _GASEntry.runTool(fn, jobId); }
function getSheetHeaders() { return _GASEntry.getSheetHeaders(); }
function getGeminiGemUrl() { return _GASEntry.getGeminiGemUrl(); }
function runBatchAI(config, jobId) { return _GASEntry.runBatchAI(config, jobId); }
function importDriveLinks(config, jobId) { _GASEntry.importDriveLinks(config, jobId); }
function extractText(config, jobId) { _GASEntry.extractText(config, jobId); }
function sampleRowsToEvaluation(jobId) { _GASEntry.sampleRowsToEvaluation(jobId); }
function prepRecipe(params) { return _GASEntry.prepRecipe(params); }
function getJobProgress(jobId) { return _GASEntry.getJobProgress(jobId); }
function getActiveRangeInfo() { return _GASEntry.getActiveRangeInfo(); }
function getDefaultRowRange() { return _GASEntry.getDefaultRowRange(); }
`,
    },
    plugins: [nodeResolve({ preferBuiltins: false }), typescript({ tsconfig: "./tsconfig.json" })],
  },

  // ── Config 2: Client bundle → dist/Sidebar.html ──────────────────────────────
  {
    input: "src/client/sidebar-entry.ts",
    output: {
      dir: "dist",
      format: "iife",
      name: "_Sidebar",
      entryFileNames: "_sidebar.js",
    },
    plugins: [
      nodeResolve({ preferBuiltins: false }),
      typescript({ tsconfig: "./tsconfig.client.json", compilerOptions: { sourceMap: false } }),
      inlineSidebarHtml({
        template: "src/Sidebar.html",
        css: "src/client/sidebar.css",
      }),
    ],
  },
];
